### ISSUE TITLE
torches have weird models

### ISSUE THREAD

**Issue by kingoscargames** [Wuzzy2/MineClone2-Bugs#248]
<img width="400" alt="screenshot_20170610_191306" src="https://user-images.githubusercontent.com/29333817/27004834-f7677660-4e10-11e7-8e21-72b37f2ccf02.png">

**Comment by kingoscargames** [comment]
i could easly fix that when i have something else than windows 10's "3d Builder"

**Comment by kingoscargames** [comment]
I fixed it once but the torch became like 45 blocks and almost the hole model was in the ground :(

**Comment by tobyplowy** [comment]
@Wuzzy2 i think @22i made models for this

**Comment by 22i** [comment]
could you test if torches still have weird models in the latest MineClone2

also what is weird about the torch models?

tested the torches and this is how they look like now since pixel perfection change
![torch](https://user-images.githubusercontent.com/17874916/29995185-d4fe8b26-8fe3-11e7-9d5f-785b0f8d8b0f.png)

**Comment by kingoscargames** [comment]
The torches shouldnt have these:
![image](https://user-images.githubusercontent.com/29333817/29995289-72541740-8fe6-11e7-871d-71a36cb219a3.png)

And the redstone torch's model is also incorrect:
![image](https://user-images.githubusercontent.com/29333817/29995333-23f02be2-8fe7-11e7-96ca-181e93524159.png)
(I used the 3x32 texture because the texture used right now has the same shape as the normal torch)

**Comment by Wuzzy2** [comment]
Yes, this is exactly what is wrong and yes, the issue is still valid.

**Comment by 22i** [comment]
@Wuzzy2  do you remember where you got the torch model from?

**Comment by Wuzzy2** [comment]
Yes, it's Minetest Game.

**Comment by 22i** [comment]
goal is to make torches look like this amiright https://www.youtube.com/watch?v=_vl0xqmlYjY

**Comment by Wuzzy2** [comment]
Wow, this looks horrible. No, please don't. I want torches to be simple. I have already simplified the texture.

It's enough for me if this gets removed:
![](https://user-images.githubusercontent.com/29333817/29995289-72541740-8fe6-11e7-871d-71a36cb219a3.png)

**Comment by 22i** [comment]
try this new torch models:

https://github.com/22i/amc/blob/master/models/amc_torch_on_floor_node.obj

https://github.com/22i/amc/blob/master/models/amc_torch_on_wall_node.obj

texture:

https://github.com/22i/amc/blob/master/textures/default_torch_on_floor.png

**Comment by Wuzzy2** [comment]
Fixed!
