### ISSUE TITLE
Hand may rarely drop as an item

### ISSUE THREAD

**Issue by Wuzzy2** [Wuzzy2/MineClone2-Bugs#388]
There is a~~n extremely~~ rare bug in which the hand may drop as an item.
I havn't figured yet out when this happens or what exactly causes the hand to be dropped.

It can't be picked up or destroyed, so this is annoying when it happens.

The bug is so rare, I think this happened to me a grand total of 2 times over the entire course of development so far.

Last evidence of this bug seen in f449f4637b3a34721c2ac1d73a86273ac81ac9b1.

**Comment by Wuzzy2** [comment]
For better tracking of this bug, there will now be big fat red error messages whenever a hand item entity is found (`itemstring==""`).

These item entities are now destroyed automatically when a player is nearby.

**Comment by kingoscargames** [comment]
This happens in the also default and other games :  
![screenshot_20170810_154051](https://user-images.githubusercontent.com/29333817/29997379-c08cfda2-9011-11e7-90be-3a8f1b050b70.png)

**Comment by Wuzzy2** [comment]
After a good amount of research, I think I have fixed this bug.

**Comment by WSDguy2014** [comment]
The glitch is still remains in 0.28.0
![screenshot_20170909_203112](https://user-images.githubusercontent.com/13905392/30242375-07471624-959e-11e7-8c98-3fc748b31cd4.png)

**Comment by WSDguy2014** [comment]
![image](https://user-images.githubusercontent.com/13905392/30242428-ed17f11e-959e-11e7-8a6f-4597f806953a.png)

I cannot take a screenshot while opening console for some reason.

**Comment by dawgdoc** [comment]
And I am still getting this error. I had just logged back into my singleplayer survival world and had not moved from my spot in my 'house'. The first bunch showed up within 30 seconds of logging in,  second bunch appeared about 3 minutes later, I think I had started gathering items from a chest to go mining. In all there were about 27 lines of error.  

I last made a pull request for MCL2 on 19 Sep. My last pull request for minetest_mcl_supplemental on 21 Aug. This is on LinuxMint 18.2 (LTS) based on Ubuntu 16.4. My minetest version is 0.4.16 from the Stable PPA. 

[mcl2-debug.txt](https://github.com/Wuzzy2/MineClone2-Bugs/files/1374027/mcl2-debug.txt)

![screenshot_20171009_012110](https://user-images.githubusercontent.com/26846591/31419742-21e9a4ec-ae03-11e7-9c91-d0b276702b40.png)

**Comment by Wuzzy2** [comment]
So. After more research, https://github.com/minetest/minetest/issues/6724 popped up.
Seems more like a Minetest thing?

Seems like the item entities get corrupted when MT crashes, resetting the itemstring to the empty string (=hand) when it got reloaded. I think I can't do much about it.

But I made a workaround. Whenever this happens, I delete the entity and make sure the weird hand is never even seen.
